# Generated by Django 3.0.7 on 2020-07-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200626_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
