# Generated by Django 3.0.7 on 2020-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
